version: "3"

services:
  firefoxc:
    image: firefoxc:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=tcp:127.0.0.1:4713
    privileged: true
    volumes:
      - /root/.Xauthority:/root/.Xauthority
      - .mozilla:/root/.mozilla
      - ffc_downloads:/root/Downloads
    devices:
      - /dev/snd
      - /dev/bus/usb
      - Pulseovernetwork
    network_mode: host
    dns:
     - 208.67.222.222
     - 208.67.220.220
     - 8.8.8.8
     - 8.8.4.4
